//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.ViewingFolder.DataBaseFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CutTheFilter
    {
        public int PersonalNumberResult { get; set; }
        public int PNWorker { get; set; }
        public int PNClient { get; set; }
        public int PNHaircut { get; set; }
        public System.DateTime DataResult { get; set; }
        public string StatusRezult { get; set; }
        public string CommentResult { get; set; }
        public string NameStatus { get; set; }
    }
}
