//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.ViewingFolder.DataBaseFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterParikhmacherView
    {
        public string PostWorker { get; set; }
        public int PersonalNumberWorker { get; set; }
        public string PSWorker { get; set; }
        public string PNWorker { get; set; }
        public string StatusWorker { get; set; }
        public string CardNumberWorker { get; set; }
        public string LoginWorker { get; set; }
        public string PasswordWorker { get; set; }
        public string NumberPhoneWorker { get; set; }
        public string EmailWorker { get; set; }
    }
}
