//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.ViewingFolder.DataBaseFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassportWorkerTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PassportWorkerTable()
        {
            this.WorkerTable = new HashSet<WorkerTable>();
        }
    
        public string PassportSeriesWorker { get; set; }
        public string PassportNumberWorker { get; set; }
        public string PassportIssuedWorker { get; set; }
        public System.DateTime DateOfIssueWorker { get; set; }
        public string DivisionCodeWorker { get; set; }
        public int PaulWorker { get; set; }
        public string PlaceOfBirthWorker { get; set; }
        public string RegistrationRegionWorker { get; set; }
        public string RegistrationPointWorker { get; set; }
        public string RegistrationStreetWorker { get; set; }
        public string RegistrationHouseWorker { get; set; }
        public string RegistrationApartmentWorker { get; set; }
        public System.DateTime DateOfBirthWorker { get; set; }
        public string DistrictWorker { get; set; }
    
        public virtual PaulTable PaulTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkerTable> WorkerTable { get; set; }
    }
}
