//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop.ViewingFolder.DataBaseFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerTable
    {
        public int PersonalNumberWorker { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public int StatusWorker { get; set; }
        public int PostWorker { get; set; }
        public string CardNumberWorker { get; set; }
        public string LoginWorker { get; set; }
        public string PasswordWorker { get; set; }
        public string NumberPhoneWorker { get; set; }
        public string EmailWorker { get; set; }
        public byte[] ImageWorker { get; set; }
        public string SurnameWorker { get; set; }
        public string NameWorker { get; set; }
        public string MiddlenameWorker { get; set; }
    
        public virtual PassportWorkerTable PassportWorkerTable { get; set; }
        public virtual PostTable PostTable { get; set; }
        public virtual SalaryCardTable SalaryCardTable { get; set; }
        public virtual StatusTable StatusTable { get; set; }
    }
}
